version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Specify labels for npm pull requests
    labels:
      - "npm"
      - "dependencies"
    # Set a limit for pull requests
    open-pull-requests-limit: 10
    # Allow up to 5 pull requests for security updates
    pull-request-branch-name:
      separator: "-"
    # Specify the version update strategy
    versioning-strategy: auto
    # Group all updates together
    groups:
      development-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "github-actions"
      - "dependencies"
